#!/bin/sh

list_time_zones() {
    find /usr/share/zoneinfo/ -type f | sed 's|/usr/share/zoneinfo/||g'
}

set_time_zone() {
    local zone=$1
    if [ -f "/usr/share/zoneinfo/$zone" ]; then
        sudo ln -sf "/usr/share/zoneinfo/$zone" /etc/localtime
        echo "Time zone set to $zone"
    else
        echo "Time zone $zone not found."
    fi
}

display_current_time_zone() {
    timedatectl | grep "Time zone"
}

case $1 in
    /l|-l|--list)
        list_time_zones
        ;;
    /s|-s|--set)
        set_time_zone $2
        ;;
    /c|-c|--current)
        display_current_time_zone
        ;;
    /?|-h|--help)
        echo "Usage: $0 [/l | /s <Time Zone> | /c | /?]"
        echo "Options:"
        echo "  /l, -l, --list       List all time zones"
        echo "  /s, -s, --set        Set the system time zone"
        echo "  /c, -c, --current    Display the current time zone"
        echo "  /?, -h, --help       Display this help message"
        ;;
    *)
        echo "Usage: $0 [/l | /s <Time Zone> | /c | /?]"
        ;;
esac